name: app_version_manager
description: A version management tool for Flutter applications
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  version_bump: app_version_manager
